//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Deck_Card = new HashSet<Deck_Card>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Faction { get; set; }
        public string Type { get; set; }
        public int Loyalty { get; set; }
        public int Defense { get; set; }
        public int Cost { get; set; }
        public string RuleText { get; set; }
        public int Attack { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deck_Card> Deck_Card { get; set; }
    }
}
