//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiagramaEntidadesArcmageContainer : DbContext
    {
        public DiagramaEntidadesArcmageContainer()
            : base("name=DiagramaEntidadesArcmageContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> CardSet { get; set; }
        public virtual DbSet<Deck> DeckSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Game> GameSet { get; set; }
        public virtual DbSet<Team> TeamSet { get; set; }
        public virtual DbSet<Tournament> TournamentSet { get; set; }
        public virtual DbSet<Player> PlayerSet { get; set; }
        public virtual DbSet<Deck_Card> Deck_CardSet { get; set; }
    }
}
