//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int Number { get; set; }
        public Nullable<int> RefereeId { get; set; }
        public Nullable<int> DeckIOneld { get; set; }
        public Nullable<int> DeckITwold { get; set; }
        public System.DateTime Hour { get; set; }
    
        public virtual Referee Referee { get; set; }
        public virtual Deck DeckOne { get; set; }
        public virtual Deck DeckTwo { get; set; }
    }
}
