//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StardadGame : Game
    {
        public int StandadTournamentId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> PlayerId1 { get; set; }
    
        public virtual StandadTournament Tournament { get; set; }
        public virtual Player PlayerOne { get; set; }
        public virtual Player PlayerTwo { get; set; }
    }
}
